version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  # Uncomment if you want to use Redis for task queue
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network
  #   restart: always

networks:
  app-network:
    driver: bridge 